### PR TITLE
This cleans up and locks down the installation and also resolves xogeny/ModelicaBook#19

### PR DESCRIPTION
**Pull request by dietmarw**

### CODE REVIEW

**Comment by xogeny** [comment]
Can I assume you tested all these changes? (*i.e.,* did a build with them)

**Comment by dietmarw** [comment]
Well all except the site part since I always even before this PR get an error and am still waiting on your feed back there ;-)

**Comment by xogeny** [comment]
Something is broken with OM.  If I try to build this `Dockerfile` or the previous version, I get:

```
Build failed: The command '/bin/sh -c apt-get update && apt-get install -y omc=1.12.0-1 omlib-modelica-3.2.2' returned a non-zero code: 100
```

Can you run the build again without any caching (*i.e.,* `docker build --no-cache ...`) on your local machine and see if it builds for you.

**Comment by dietmarw** [comment]
The OM team have pushed a new update to the stable branch and did not keep the older versions. I've discussed this with @sjoelund and he set up now an archive mirror for the two latest LTS versions. PR is coming up :-)

**Pull request merged**
